### ISSUE TITLE
if NodeClaims are not satisfied, Karpenter still create the NIC and does no delete it

### ISSUE THREAD

**Issue by philwelz** [Azure/karpenter#67]
### Version

__Karpenter Version:__ 0.29.2

__Kubernetes Version:__ v1.27.7

### Expected Behavior

When a NodeClaim cant be satisfied and is removed, the NIC should not be created or deleted afterwards.

### Actual Behavior

Karpenter creates and deletes the NodeClaims but does not remove the NIC. So you end up with a lot of NICs in the `MC_` resource group.

### Steps to Reproduce the Problem

run` kubectl scale deploy inflate --replicas 300 -n default` and  watch the Karpenter pods logs, you will see for example this error: `\"error\": {\n    \"code\": \"OperationNotAllowed\",\n    \"message\": \"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: northeurope, Current Limit: 65, Current Usage: 54, Additional Required: 96, (Minimum) New Limit Required: 150.`

Karpenter creates the NodeClaim and you will see them appear and disappear (`kubectl get nodeclaim -w`). For every NodeClaim a NIC is created but not deleted. So you end up with a lot of NICs in the `MC_` resource group.

### Resource Specs and Logs

{"level":"ERROR","time":"2023-12-15T21:40:08.562Z","logger":"controller.nodeclaim.lifecycle","message":"creating instance, insufficient capacity, regional on-demand vCPU quota limit for subscription has been reached. To scale beyond this limit, please review the quota increase process here: https://learn.microsoft.com/en-us/azure/quotas/regional-quota-requests","commit":"76a3b5a-dirty","nodeclaim":"general-purpose-rmshj","nodepool":"general-purpose"}
{"level":"INFO","time":"2023-12-15T21:40:08.601Z","logger":"controller.nodeclaim.termination","message":"deleted nodeclaim","commit":"76a3b5a-dirty","nodeclaim":"general-purpose-rmshj","nodepool":"general-purpose","node":"","provider-id":""}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
@philwelz  I have the fix in the linked pr if you want to take a look!

**Comment by philwelz** [comment]
Thanks @Bryce-Soghigian ! As im not that good at Go i deployed from your branch and the issue is still the same :( from the logs i could see this should be the correct version with your fix : `"commit":"0f27f21-dirty"` and your fix is https://github.com/Azure/karpenter/commit/0f27f212b19a1392a14db81576391bf43a4f67f8 .

**Comment by Bryce-Soghigian** [comment]
Hey @philwelz, I just pushed some new code, seems we have gotten past the extra sad case, but there is another error I caught as well. 

# Fix for Leftover NICs in Karpenter
Here is an initial write up of the testing I performed.
Scale Up Operations
We conducted 2 scale-up operations. The first scale up to 10 nodes took 55 seconds, with the readiness of the nodes monitored with the very official benchmark of spamming k get nodeclaims until we saw all of them were ready.
```
~/dev/karpenter (bsoghigian/nic-fix*) » k get nodeclaims.karpenter.sh                                             sillygoose@Bryces-MacBook-Pro
NAME                       TYPE               ZONE       NODE                           READY   AGE
sm-general-purpose-4c4mg   Standard_D2ls_v5   eastus-2   aks-sm-general-purpose-4c4mg   True    55s
sm-general-purpose-52hbw   Standard_D2ls_v5   eastus-3   aks-sm-general-purpose-52hbw   True    55s
sm-general-purpose-7bwx5   Standard_D2ls_v5   eastus-3   aks-sm-general-purpose-7bwx5   True    55s
... Removed 7 nodes for brevity
```
Subsequent scale-ups were performed to 100 nodes:

```bash
~/dev/karpenter (bsoghigian/nic-fix*) » k get nodes | wc -l                                                       sillygoose@Bryces-MacBook-Pro
     100
```

## Checking for Ghost NICs
Checking, I hit the Quota error 78 times in this scale up run
```
~/dev/karpenter (bsoghigian/nic-fix*) » k logs -n karpenter karpenter-769b948689-dnc8d| grep OperationNotAllowed | wc -
      78
```

To check for ghost NICs at 100 nodes, I looked at the portal, checked with a script, and with `make az-resc`. 
I only see 1 ghost NIC, whereas with the previous logic we would see 78, one for each failure to provision the vm. 
```
~/dev/karpenter (bsoghigian/nic-fix*) » ./nic.sh                                                                  sillygoose@Bryces-MacBook-Pro
NICs without a VM in the resource group 'MC_storagetest2_karpenter8_eastus':
"/subscriptions/(redacted-subscription)/resourceGroups/MC_storagetest2_karpenter8_eastus/providers/Microsoft.Network/networkInterfaces/aks-sm-general-purpose-6wtkg"
```

### While its nice to see the improvement, what is the root cause for the single ghost nic? 
Grepping through the karpenter logs for this resource `aks-sm-general-purpose-6wtkg`, It looks like we ran into a new Error Code `NicReservedForAnotherVm`. Here is the full breakdown of actions we took on the `aks-sm-general-purpose-6wtkg` NIC, VM, and machine. 
### Steps taken on aks-sm-general-purpose-6wtkg from Karpenter Log

1. **Creating Network Interface (Success)**
   - **Timestamp**: `2023-12-17T05:31:18.458Z`
   - **Operation**: Creation of a network interface named `aks-sm-general-purpose-6wtkg`.
   - **Status**: Successful creation of the network interface.

2. **Creating Virtual Machine (Initial Attempt)**
   - **Timestamp**: `2023-12-17T05:31:20.158Z`
   - **Operation**: Attempt to create a virtual machine named `aks-sm-general-purpose-6wtkg`, with the specification `Standard_D2ls_v5`.
   - **Status**: Initial attempt, status not yet known from this log entry.

3. **Error in Creating Virtual Machine (Quota Exceeded)**
   - **Timestamp**: `2023-12-17T05:31:20.555Z`
   - **Operation**: Creation of the virtual machine `aks-sm-general-purpose-6wtkg`.
   - **Error**: The operation failed due to exceeding the approved quota for `standardDLSv5Family Cores`. The current limit is 100, and the creation of this VM would require an additional 2 cores, bringing the required total to 102.
   - **Action Required**: A quota increase request is necessary, with instructions to submit it via a provided URL.
4. **Error Deleting Network Interface (Reserved NIC)**
   - **Timestamp**: `2023-12-17T05:31:20.841Z`
   - **Operation**: Attempt to delete the network interface `aks-sm-general-purpose-6wtkg`.
   - **Error**: Failure due to the network interface being reserved for another Virtual Machine for 180 seconds. This implies that the network interface cannot be deleted immediately as it is temporarily locked or reserved.


```json
{"level":"DEBUG","time":"2023-12-17T05:31:18.458Z","logger":"controller.nodeclaim.lifecycle","message":"Creating network interface aks-sm-general-purpose-6wtkg","commit":"25adaf2-dirty","nodeclaim":"sm-general-purpose-6wtkg","nodepool":"sm-general-purpose"}
{"level":"DEBUG","time":"2023-12-17T05:31:20.158Z","logger":"controller.nodeclaim.lifecycle","message":"Successfully created network interface: /subscriptions/(subscription-redacted)/resourceGroups/MC_storagetest2_karpenter8_eastus/providers/Microsoft.Network/networkInterfaces/aks-sm-general-purpose-6wtkg","commit":"25adaf2-dirty","nodeclaim":"sm-general-purpose-6wtkg","nodepool":"sm-general-purpose"}
{"level":"DEBUG","time":"2023-12-17T05:31:20.158Z","logger":"controller.nodeclaim.lifecycle","message":"Creating virtual machine aks-sm-general-purpose-6wtkg (Standard_D2ls_v5)","commit":"25adaf2-dirty","nodeclaim":"sm-general-purpose-6wtkg","nodepool":"sm-general-purpose"}
{"level":"ERROR","time":"2023-12-17T05:31:20.555Z","logger":"controller.nodeclaim.lifecycle","message":"Creating virtual machine \"aks-sm-general-purpose-6wtkg\" failed: PUT https://management.azure.com/subscriptions/(subscription-redacted)/resourceGroups/MC_storagetest2_karpenter8_eastus/providers/Microsoft.Compute/virtualMachines/aks-sm-general-purpose-6wtkg\n--------------------------------------------------------------------------------\nRESPONSE 409: 409 Conflict\nERROR CODE: OperationNotAllowed\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"OperationNotAllowed\",\n    \"message\": \"Operation could not be completed as it results in exceeding approved standardDLSv5Family Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 100, Current Usage: 100, Additional Required: 2, (Minimum) New Limit Required: 102. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/#blade/Microsoft_Azure_Capacity/UsageAndQuota.ReactView/Parameters/%7B%22subscriptionId%22:%22(subscription-redacted)%22,%22command%22:%22openQuotaApprovalBlade%22,%22quotas%22:[%7B%22location%22:%22eastus%22,%22providerId%22:%22Microsoft.Compute%22,%22resourceName%22:%22standardDLSv5Family%22,%22quotaRequest%22:%7B%22properties%22:%7B%22limit%22:102,%22unit%22:%22Count%22,%22name%22:%7B%22value%22:%22standardDLSv5Family%22%7D%7D%7D%7D]%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/per-vm-quota-requests\"\n  }\n}\n--------------------------------------------------------------------------------\n","commit":"25adaf2-dirty","nodeclaim":"sm-general-purpose-6wtkg","nodepool":"sm-general-purpose"}
{"level":"ERROR","time":"2023-12-17T05:31:20.555Z","logger":"controller.nodeclaim.lifecycle","message":"virtualMachine.BeginCreateOrUpdate for VM \"aks-sm-general-purpose-6wtkg\" failed: PUT https://management.azure.com/subscriptions/(subscription-redacted)/resourceGroups/MC_storagetest2_karpenter8_eastus/providers/Microsoft.Compute/virtualMachines/aks-sm-general-purpose-6wtkg\n--------------------------------------------------------------------------------\nRESPONSE 409: 409 Conflict\nERROR CODE: OperationNotAllowed\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"OperationNotAllowed\",\n    \"message\": \"Operation could not be completed as it results in exceeding approved standardDLSv5Family Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 100, Current Usage: 100, Additional Required: 2, (Minimum) New Limit Required: 102. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/#blade/Microsoft_Azure_Capacity/UsageAndQuota.ReactView/Parameters/%7B%22subscriptionId%22:%22(subscription-redacted)%22,%22command%22:%22openQuotaApprovalBlade%22,%22quotas%22:[%7B%22location%22:%22eastus%22,%22providerId%22:%22Microsoft.Compute%22,%22resourceName%22:%22standardDLSv5Family%22,%22quotaRequest%22:%7B%22properties%22:%7B%22limit%22:102,%22unit%22:%22Count%22,%22name%22:%7B%22value%22:%22standardDLSv5Family%22%7D%7D%7D%7D]%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/per-vm-quota-requests\"\n  }\n}\n--------------------------------------------------------------------------------\n","commit":"25adaf2-dirty","nodeclaim":"sm-general-purpose-6wtkg","nodepool":"sm-general-purpose"}
{"level":"ERROR","time":"2023-12-17T05:31:20.841Z","logger":"controller.nodeclaim.lifecycle","message":"networkInterface.Delete for aks-sm-general-purpose-6wtkg failed: DELETE https://management.azure.com/subscriptions/(subscription-redacted)/resourceGroups/MC_storagetest2_karpenter8_eastus/providers/Microsoft.Network/networkInterfaces/aks-sm-general-purpose-6wtkg\n--------------------------------------------------------------------------------\nRESPONSE 400: 400 Bad Request\nERROR CODE: NicReservedForAnotherVm\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"NicReservedForAnotherVm\",\n    \"message\": \"Nic(s) in request is reserved for another Virtual Machine for 180 seconds. Please provide another nic(s) or retry after 180 seconds. Reserved VM: /subscriptions/(subscription-redacted)/resourceGroups/MC_storagetest2_karpenter8_eastus/providers/Microsoft.Compute/virtualMachines/aks-sm-general-purpose-6wtkg\",\n    \"details\": []\n  }\n}\n--------------------------------------------------------------------------------\n","commit":"25adaf2-dirty","nodeclaim":"sm-general-purpose-6wtkg","nodepool":"sm-general-purpose"}
```
## Summary
With the change, we fix most of the NIC errors, but still need to have some followup work seeing the best way to deal with `NicReservedForAnotherVm`. I want to do some additional testing on the old code, just to show the contrast in my statement of their being 78 ghost nics, for each vm creation error vs the 1 ghost nic.

**Comment by Bryce-Soghigian** [comment]
I have a couple of additional scenarios I want to test, but wanted to share progress here.

**Comment by philwelz** [comment]
hey @Bryce-Soghigian , when calling `make az-resc` you do net get all nics as they do not have correct label. I added an PR to fix that: https://github.com/Azure/karpenter/pull/74

**Comment by Bryce-Soghigian** [comment]
@philwelz  merging in this change, should significantly improve the scenario, there is still an edgecase but it wont leave 100s of nics now
